sfc/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('checkssn', views.checkssn, name='checkssn'),
    path('scankeypart', views.scankeypart, name='scankeypart'),
    path('testssn', views.testssn, name='testssn'),
    path('checkkeypart', views.checkkeypart, name='checkkeypart'),
    path('getpart', views.getpart, name='getpart'),
    path('get-delivery-number', views.getDeliveryNumber, name = 'getDeliveryNumber'),

]   

sfc/manufacturing/urls.py
from django.urls import path
from . import views

app_name = 'manufacturing'
urlpatterns = [
    path('', views.home, name='home'),
    path('reset_confirm/', views.reset_confirm, name='reset_confirm'),

    path('label_center/', views.label_center, name='label_center'),
    path('label_center/get-serial-numbers', views.get_serial_numbers, name='get-sns-by-wo'),
    path('so_list/', views.so_list, name='so_list'),
    path('serialnumber_log/', views.serialnumber_log, name='serialnumber_log'),

# sidebar tabs ###########
    path('sidebar/sub_config/', views.sub_config, name='sub_config'),
    path('sidebar/sub_toolbox/', views.sub_toolbox, name='sub_toolbox'),
    path('sidebar/sub_wip/', views.sub_wip, name='sub_wip'),
    path('sidebar/sub_shipping_manager/', views.sub_shipping_manager, name='sub_shipping_manager'),
    path('sidebar/sub_qms/', views.sub_qms, name='sub_qms'),
    path('sidebar/sub_wms/', views.sub_wms, name='sub_wms'),

#### user profile ###############
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('add_profile/', views.user_add_profile, name='add_profile'),
    path('users/add_profiles/', views.UsersProfilesAdd.as_view(), name='users_add_profiles'),
    path('users/profiles_list/', views.UsersProfilesListView.as_view(), name='users_profiles_list'),
    path('users/profiles_delete/<int:pk>/', views.UsersProfilesDelete.as_view(), name='users_profile_delete'),
    path('users/profiles_update/<int:pk>/', views.UsersProfilesUpdate.as_view(), name='users_profiles_update'),
]

urlpatterns += [
    path('accounts/signup/', views.signup, name='signup'),
    path('signup/', views.signup_sidebar, name='signup_sidebar'),
    path('user/myprofile_detail/<int:pk>/', views.UserProfileListView.as_view(), name='profile_detail'),
    path('user/myprofile_edit/', views.update_profile, name='user_top_update'),
    path('password/', views.change_password, name='change_password'),
]

urlpatterns += [
    path('management/user/', views.UserListView.as_view(), name='user_list'),
    path('management/user-delete/<int:pk>/', views.UserDelete.as_view(), name='user-delete'),
    path('search/user/', views.SearchUserView.as_view(), name='search_user'),
    path('management/user-update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    path('management/user-update/profile/<int:pk>/', views.UsersSidebarProfilesUpdate.as_view(), name='users_profiles_update_sidebar'),
    path('users_update_profiles_view/<id>/', views.users_update_profiles_view, name='update_profiles_view'),
    path('profiles_detail_view/<id>/', views.profiles_detail_view, name='profiles_detail_view'),
    ##  permission #####
    path('management/user-add-permissions/<int:pk>/', views.UserAddPermissionUpdate.as_view(), name='add-permissions'),
    path('management/user-permissions/', views.UserListPermissionsView.as_view(), name='permissions'),
    ## group ##
     path('management/user-group/', views.CreateUserGroup.as_view(), name='user-group'),
     path('management/user-group-list/', views.UserGroupListView.as_view(), name='user_group_list'),
     path('management/user-group/update/<int:pk>/', views.UserGroupUpdate.as_view(), name='user_group_update'),
     path('management/user-group-delete/<int:pk>/', views.UserGroupDelete.as_view(), name='user-group-delete'),
]

urlpatterns += [
    path('wip/production-flow/test-station', views.SerialNumberTestForm.as_view(), name='production_flow_station'),
    path('tool_box/workorder_list', views.WorkOrderListView.as_view(), name='workorder_list'),
    path('tool_box/workorder_list_reverse', views.WorkOrderReverseListView.as_view(), name='workorder_list_reverse'),
    path('tool_box/workorder-detail/<int:pk>',views.WorkOrderDetailDetailView.as_view(), name='workorder-detail'),
    path('tool_box/workordermanager-wo-detail/<pk>', views.workorder_detail, name='workordermanager-wo-detail'),
    path('tool_box/workordermanager-sn-detail/<pk>', views.serialnumber_detail, name='workordermanager-sn-detail'),
    path('tool_box/workorder_list/status/<pk>/', views. WorkOrderEditUpdate.as_view(), name='workorder-status'),
    path('tool_box/label-center', views.label_center, name='label-center'),
    path('tool_box/search_by_sn', views.SearchResultsBySNView.as_view(), name='search_by_sn'),
    path('tool_box/search_by_wo', views.SearchResultsByWOView.as_view(), name='search_by_wo'),
    path('tool_box/label_create', views.label_create, name='label-create'),
    path('tool_box/serialnumber_list', views.SerialNumberListView.as_view(), name='serialnumber_list'),
    path('tool_box/serialnumber_list/edit/', views.serialnumber_update, name='serialnumber_update'),
    path('tool_box/serialnumber_detail/<str:pk>/', views.SNManagereDetail.as_view(), name='serialnumber_detail'),

    path('wip/serialnumber/detail/', views.SerialNumberDetail.as_view(), name='serialnumber-detail'),
    path('modalform/workorder/', views.WorkOrderIndex.as_view(), name='index-workorder'),
    path('wip/forms/last_button/', views.post_generate_sn, name='last_button'),
    path('master-list/', views.MaterialMasterListView.as_view(), name='master_list'),

]

urlpatterns += [
    path('tool_box/hold_station', views.hold_station, name='hold_station'),
    path('tool_box/UnHold/<str:hold_id>/', views.UnHold, name='UnHold'),
    path('tool_box/HoldEdit/<str:hold_id>/', views.HoldEdit, name='HoldEdit'),
    path('tool_box/HoldAdd', views.HoldAdd, name='HoldAdd'),
]

sfc/sfc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import path

from django.contrib.auth import views as auth_views





urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('manufacturing/', include('manufacturing.urls')),
    path('config/git', include('git.urls')),
    path('config/', include('maskconfig.urls',namespace='maskconfig')),
    path('line/', include('line.urls')),
    path('line/', include('rules.urls')),
    path('api/', include('api.urls')),
    path('offline_station/', include('offline_station.urls')),
    path('shipping/', include('shipping.urls')),
    path('qms/', include('qms.urls')),
    path('wms/', include('wms.urls')),
    
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='manufacturing/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.urls import reverse_lazy
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('password_reset/', auth_views.password_reset, name='password_reset'),
    # path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]


urlpatterns += [

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_formIMS.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_doneIMS.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirmIMS.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_completeIMS.html'
         ),
         name='password_reset_complete'),
]


sfc/shipping/urls.py
from django.urls import path
from . import views

app_name = 'shipping'

urlpatterns = [
    ######################### palletization #############################################
    path('wip/palletize/', views.PalletStationDetailView.as_view(), name='pallet_station'),
    path('wip/palletize/add_sn/', views.add_sn_view, name='pallet_add_sn'),
    path('wip/palletize/delete/<str:pk>/', views.PalletDetail.as_view(), name='pallet_detail_delete'),
    path('wip/palletize/delete/<str:pk>', views.delete_sn_view, name='delete_sn'),
    path('wip/palletize/save_dimension/', views.save_dimension, name='save_dimension'),
    path('wip/palletize/save_dimension/<str:pk>/', views.PalletDetail.as_view(), name='after_save_dimensions'),
    path('wip/palletize/create_new_pallet/', views.create_new_pallet, name='create_new_pallet'),
    path('wip/palletize/create_new_pallet/<str:pk>/', views.PalletDetail.as_view(), name='after_create_new'),

    path('wip/palletize/validate-sn/', views.validate_sn_json, name='validate_sn_json'),
    path('wip/palletize/delete-sn/', views.delete_sn_json, name='delete_sn_json'),
    path('wip/palletize/add-sn/', views.add_sn_json, name='add_sn_json'),

    path('wip/palletize/add/', views.add_sn_test_view, name='add_sn_to_pallet'),
    path('wip/palletize/add/<str:pk>', views.PalletDetail.as_view(), name='pallet_detail'),
    path('wip/palletize/create_new_pallet_id/', views.create_pallet_id, name='create_new_pallet_id'),
   # path('wip/palletize/create_new_pallet_id/<str:pk>/', views.PalletDetail.as_view(), name='after_create_new_id'),

    # #######################  ship out ###########################################
    path('wip/ship_out/', views.SalesOrderEnterView.as_view(), name='ship_out_station'),
    path('wip/ship_out/success/', views.SalesOrderSuccessView.as_view(), name='ship_out_success'),
    path('wip/ship_out/detail/<str:pk>/', views.SalesDetail.as_view(), name='ship_out_detail'),
    path('wip/shipout/process/', views.Process, name='process'),
    path('wip/shipout/validate_sn/', views.ValidateSN, name='validate_sn'),
    path('wip/shipout/validate_sku/', views.ValidateSKU, name='validate_sku'),

    # ####################### truck load #############################################
    path('wip/truckload/', views.TruckLoadView.as_view(), name='truckload_station'),
    path('wip/truckload/getpallet/', views.get_pallets_by_dn, name='get_pallet'),
    path('wip/truckload/savetruckload/', views.SaveTruckLoad, name='save_truck'),

    # ####################### salesorder #############################################
    path('tool_box/salesorder_list/', views.SalesOrderListView.as_view(), name='salesorder_list'),
    path('tool_box/salesorder_list/detail/<int:pk>/', views.SalesOrderDetailView.as_view(), name='salesorder_detail'),

    # ####################### deliverynumber #############################################
    path('tool_box/deliverynumber_list/', views.DeliveryNumberListView.as_view(), name='deliverynumber_list'),
    path('tool_box/deliverynumber_list/detail/<str:pk>/', views.DeliveryNumberDetailView.as_view(), name='deliverynumber_detail'),


    path('wip/unpalletize/', views.UNPalletStationDetailView.as_view(), name='unpallet_station'),
    path('wip/unpalletize/detail/<str:pk>', views.UNPalletDetail.as_view(), name='unpallet_detail'),


    path('pallet-printer', views.PalletTemplateForm.as_view(), name="print_pallet_list"),


    ]

sfc/manufacturing/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth.models import User
from .models import Profile, TestingResult, RepairDetail, Label, RepairMain
from django.contrib.auth.models import Group, Permission
from django.contrib.admin.widgets import FilteredSelectMultiple


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # group = forms.ModelChoiceField(queryset=Group.objects.all(),
    #                                required=True)
    # groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all())
    # groups = forms.ManyToManyField(Group, through='User')
    # plant_code = forms.ModelChoiceField(queryset=Profile.objects.all(),
    #                                required=True)
    department = forms.CharField(max_length=100)

    # TYPE_CODE = (
    #     ('FIIX', 'FIIX'),
    # )
    # plant_code = forms.ChoiceField(choices=TYPE_CODE)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',
                  'password1', 'password2', 'department')


class SignUpLogInForm(UserCreationForm):
    department = forms.CharField(max_length=100)

    # TYPE_CODE = (
    #     ('FIIX', 'FIIX'),
    #     ('TEST', 'TEST'),
    # )
    # plant_code = forms.ChoiceField(choices=TYPE_CODE)

    class Meta:
        model = User
        fields = ('department', 'groups')


class UserProfileForm(forms.Form):
    location = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    state = forms.CharField(max_length=100)
    role = forms.CharField(max_length=100)
    department = forms.CharField(max_length=100)


################ group ###################


class UserGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
        widgets = {
            'permissions': FilteredSelectMultiple("Permission", False, attrs={'rows': '2'}),
        }


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'


############# user and profile form ##########
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'groups')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('department',)

    # ############## users id update form ########


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user', 'department')  # Note that we didn't mention user field here.

    def save(self, user=None):
        user_profile = super(UserProfileForm, self).save(commit=False)
        if user:
            user_profile.user = user
        user_profile.save()
        return user_profile


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ('name', 'zpl')


#################### repair form ########################
# class OutPNForm(forms.Form):
#     out_part_no = forms.CharField(max_length=30)
#     message = forms.CharField(max_length=200, widget=forms.TextInput)
#
#
# class TestResultForm(forms.Form):
#     result = forms.CharField(max_length=1)


class OutPNForm(forms.Form):
    fields = '__all__'

    #     lookup model instances
    def lookup(self):
        self.data['replacement'] = "foobar"
        print(self.data.get('replacement'))

    #     add non appended data
    def entry(self):
        pass


class RepairMainForm(forms.Form):
    fields = ['result']


######## password reset email ###############

sfc/manufacturing/templates/manufacturing/snmanager/snmanager_detail.html
{% include 'manufacturing/include/header.html' %}
<!--header end-->
{% load static %}
<link rel="stylesheet" href="{% static 'css/maskconfig/style.css' %}">
{% include 'manufacturing/include/sidebar.html' %}
{% include 'manufacturing/include/error-modal-style.html' %}
<section id="main-content">
  <section class="wrapper">
       <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Dashboard</a></li>
                <!--<li><i class="fa icon_toolbox"></i><a href="{% url 'manufacturing:sub_toolbox' %}">Tool Box</a></li>-->
                    <li><i class="fa fa-barcode"></i><a href="{% url 'manufacturing:salesorder_list' %}">Serial Number Manager</a></li>
                </ol>
            </div>
        </div>

       <div class="row" >
          <div class="col-lg-12">
            <section class="panel">
                <div class="whole whole-table">
                <div class="main-content">
                    <div class="nav-user-search  clearfix header-search-box">
                          <div class="nav top-menu top-button">
                              <form  class="navbar-form" id="search" action="{% comment %}{% url 'manufacturing:so_list' %}{% endcomment %}" method="get">
                                 <div class="nav search-row list-title-search" id="top_menu">
                                     <div><input class="form-control" name="q" class="form-control" type="text" placeholder="SN Number" value="{{ values.q }}" autofocus required></div>
                                     <div style="width: 30px;">
                                     <button class="nav-user-search-icon" type="submit" style="padding: 0;">
                                          <i _ngcontent-crw-c2="" style="font-size: 3rem;" class="icon_search-2 search-icon text-muted i-Magnifi-Glass1"></i>
                                     </button>
                                    </div>
                                 </div>
                            </form>
                          </div>
                        </div>
                   </div>

                       <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="printer-error-modal" aria-hidden="true" id="printer-error-modal">
                         <div class="modal-dialog modal-sm">
                           <div class="modal-content">
                           </div>
                         </div>
                       </div>
                          <table class="table table-striped table-advance table-hover" id="print-sn-table">
                            <tbody>
                              <tr class="table-header">
                                <th> No.</th>
                                <th><i class="icon_cogs"></i> Serial Number No.</th>
                                <th><i class="icon_cogs"></i> WorkOrder</th>
                                <th><i class="icon_cogs"></i> Model</th>
                                <th><i class="icon_cogs"></i> Status</th>
                                <th><i class="icon_cogs"></i> Station{{ serialnumber.pk }}</th>
                                <th ><i></i> &nbsp; Update</th>
                              </tr>

                                  <iframe name="formDestination" style="display: none;"></iframe>
                                <tr>
                                  <th><p>&nbsp;&nbsp;{{ forloop.counter }}</p></th>
                                  <th><p>{{ serialnumber.serial_number}} {{ serialnumber.pk }}</p></th>
                                  <th><p>{{ serialnumber.workorder_id }}</p></th>
                                  <th><p>{{ serialnumber.model_id  }}</p> </th>
                                  <th> <p>{{ serialnumber.status }}</p></th>
<!--                                ######################## options ############################    -->
                                      {% comment %}<form class="navbar-form" id="search1" action="{% url 'manufacturing:update-serialnumber_list-row' serialnumber.pk  %}" method="get" enctype="multipart/form-data" target="formDestination">{% endcomment %}
                                         {% csrf_token %}
                                         {{ form.non_field_errors }}
                                         {{ form.source.errors }}
                                        {{ form.source }}

                                          <script>
                                             document.getElementById('search1').searchID.onchange = function() {
                                             var newaction = this.value;
                                             document.getElementById('search1').action = newaction;
                                             };
                                            </script>
                                  <th  contenteditable="true" class="column-action">
                                       <div class="edit-save-1 hover" id="edit-save-1">
                                        {% comment %} <select name="station" class="form-control form-control-selection" style="padding-left: 5px;">
                                                <option selected="true" value="{{ serialnumber.station_id }}">{{ serialnumber.station_id }}</option>
                                             {% if station_list %}
                                             {% for station in station_list %}
                                                 <option style="color: #222;" class="query-button" value="{{ station.pk }}">{{ station.pk }}</option>
                                                {% endfor %}
                                              {% endif %}
                                         </select>{% endcomment %}
                                           <p><input type="text" class="edit-input-1 edit-row" name="serial_number" value="{{ serialnumber.serial_number}}"></p>
                                       </div>
                                  </th>

                                    <form class="navbar-form" id="search1" action="{% url 'manufacturing:update-serialnumber_list-row' serialnumber.pk  %}" method="get" {% comment %}enctype="multipart/form-data" target="formDestination"{% endcomment %}>
                                      <th>
                                        <div>
                                            {% load static %}
                                              <button type="submit" id="save-button-1"  style="background: none; border: none;" class="icon-text-mask icon-text  btn-confirm simple-confirm">
                                                <img  src="{% static 'svg/submit-id.svg' %}" alt="icon"><span>Save</span></button>
                                         </div>
                                      </th>
                                     </form>
                                </tr>
                            </tbody>
                          </table>
                        {% include 'manufacturing/include/pagination.html' %}
                     </div>
                 </section>
               </div>
            </div>
    </section>
</section>
{% load static %}
 <script src="{% static 'js/line/warning-modal.js' %}"></script>
 <script src="{% static 'js/manufacturing/inline.js' %}"></script>
<!-- javascripts -->
{% include 'manufacturing/include/javascript-sidebar.html' %}
</body>
</html>

sfc/manufacturing/templates/manufacturing/snmanager/snmanager_update.html
{% include 'manufacturing/include/header.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/maskconfig/style.css' %}">
{% include 'manufacturing/include/sidebar.html' %}
{% include 'manufacturing/include/error-modal-style.html' %}
<section id="main-content">
  <div class="wrapper">
       <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Dashboard</a></li>
                    <!--<li><i class="icon_genius"></i><a href="{% url 'manufacturing:sub_toolbox' %}">Assembly Manager</a></li>-->
                    <li><i class="fa fa-th-list"></i><a href="{% url 'manufacturing:serialnumber_list' %}">Serial Number Manager</a></li>
                </ol>
            </div>
        </div>

      <div class="row" >
          <div class="col-lg-12">
            <section class="panel">
                <div class="whole whole-table">
                    <div class="main-content">
                        <div class="nav-user-search  clearfix header-search-box">
                          <div class="nav top-menu top-button">
                              <form  class="navbar-form" id="search" action="{% comment %}{% url 'manufacturing:so_list' %}{% endcomment %}" method="get">
                                 <div class="nav search-row list-title-search" id="top_menu">
                                     <div><input class="form-control" name="q" class="form-control" type="text" placeholder="SN Number" value="{{ values.q }}" autofocus required></div>
                                     <div style="width: 30px;">
                                     <button class="nav-user-search-icon" type="submit" style="padding: 0;">
                                          <i _ngcontent-crw-c2="" style="font-size: 3rem;" class="icon_search-2 search-icon text-muted i-Magnifi-Glass1"></i>
                                     </button>
                                    </div>
                                 </div>
                            </form>
                          </div>
                        </div>
                    </div>
                    <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="printer-error-modal" aria-hidden="true" id="printer-error-modal">
                     <div class="modal-dialog modal-sm">
                       <div class="modal-content">
                       </div>
                     </div>
                    </div>

                    <div id="maxheight">
                      <table class="table table-striped table-advance table-hover" id="print-sn-table">
                        <tbody>
                          <tr class="table-header">
                            <th> No.</th>
                            <th><i class="icon_cogs"></i> Serial Number No.</th>
                            <th><i class="icon_cogs"></i> WorkOrder</th>
                            <th><i class="icon_cogs"></i> Model</th>
                            <th><i class="icon_cogs"></i> Status</th>
                            <th><i class="icon_cogs"></i> Station</th>
                            <th ><i></i> &nbsp; Update</th>
                          </tr>
                          {% comment %}{% for serialnumber in serialnumber_list %}{% endcomment %}
                              <iframe name="formDestination" style="display: none;"></iframe>
                            <tr>
                              <th><p>&nbsp;&nbsp;{{ forloop.counter }}</p></th>
                              <th><p>{{ serialnumber.serial_number}} {{ serialnumber.pk }}</p></th>
                              <th><p>{{ serialnumber.workorder_id }}</p></th>
                              <th><p>{% comment %}{{ serialnumber.model_id  }}{% endcomment %}</p> </th>
                              <th> <p>{{ serialnumber.status }}</p></th>
                              <form class="navbar-form" id="search1" action="" method="post">
                                 {% csrf_token %}
                                 {{ form.non_field_errors }}
                                 {{ form.source.errors }}
                                 {{ form.source }}
                                  <script>
                                     document.getElementById('search1').searchID.onchange = function() {
                                     var newaction = this.value;
                                     document.getElementById('search1').action = newaction;
                                     };
                                    </script>
                               <th  contenteditable="true" class="column-action">
                                   <div class="edit-save-1 hover" id="edit-save-1">
                                        {% comment %} <select name="station" class="form-control form-control-selection" style="padding-left: 5px;">
                                             <option selected="true" value="{{ serialnumber.station }}">{{ serialnumber.station }}</option>
                                             {% if station_list %}
                                             {% for station in station_list %}
                                             <option style="color: #222;" class="query-button" value="{{ station.pk }}">{{ station.pk }}</option>
                                             {% endfor %}
                                             {% endif %}
                                         </select>{% endcomment %}
                                       <p><input type="text" class="edit-input-1 edit-row" name="station" value="{{ serialnumber.station_id}}"></p>
                                   </div>
                               </th>
                               <th>
                                    <div>
                                      {% load static %}
                                      <button type="submit" id="save-button-1"  style="background: none; border: none;" class="icon-text-mask icon-text  btn-confirm simple-confirm">
                                      <img  src="{% static 'svg/submit-id.svg' %}" alt="icon"><span>Save</span></button>
                                    </div>
                               </th>
                               </form>
                            </tr>
                        </tbody>
                      </table>
                    </div>
                    {% include 'manufacturing/include/pagination.html' %}
                     </div>
                 </section>
               </div>
            </div>
        </div>
   </section>
</section>
{% load static %}
<script src="{% static 'js/line/warning-modal.js' %}"></script>
<script src="{% static 'js/manufacturing/inline.js' %}"></script>
{% include 'manufacturing/include/javascript-sidebar.html' %}
</body>
</html>