sfc/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('checkssn', views.checkssn, name='checkssn'),
    path('scankeypart', views.scankeypart, name='scankeypart'),
    path('testssn', views.testssn, name='testssn'),
    path('checkkeypart', views.checkkeypart, name='checkkeypart'),
    path('getpart', views.getpart, name='getpart'),
    path('get-delivery-number', views.getDeliveryNumber, name = 'getDeliveryNumber'),

]   

sfc/manufacturing/urls.py
from django.urls import path
from . import views

app_name = 'manufacturing'
urlpatterns = [
    path('', views.home, name='home'),
    path('reset_confirm/', views.reset_confirm, name='reset_confirm'),

    path('label_center/', views.label_center, name='label_center'),
    path('label_center/get-serial-numbers', views.get_serial_numbers, name='get-sns-by-wo'),
    path('so_list/', views.so_list, name='so_list'),
    path('serialnumber_log/', views.serialnumber_log, name='serialnumber_log'),

# sidebar tabs ###########
    path('sidebar/sub_config/', views.sub_config, name='sub_config'),
    path('sidebar/sub_toolbox/', views.sub_toolbox, name='sub_toolbox'),
    path('sidebar/sub_wip/', views.sub_wip, name='sub_wip'),
    path('sidebar/sub_shipping_manager/', views.sub_shipping_manager, name='sub_shipping_manager'),
    path('sidebar/sub_qms/', views.sub_qms, name='sub_qms'),
    path('sidebar/sub_wms/', views.sub_wms, name='sub_wms'),

#### user profile ###############
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('add_profile/', views.user_add_profile, name='add_profile'),
    path('users/add_profiles/', views.UsersProfilesAdd.as_view(), name='users_add_profiles'),
    path('users/profiles_list/', views.UsersProfilesListView.as_view(), name='users_profiles_list'),
    path('users/profiles_delete/<int:pk>/', views.UsersProfilesDelete.as_view(), name='users_profile_delete'),
    path('users/profiles_update/<int:pk>/', views.UsersProfilesUpdate.as_view(), name='users_profiles_update'),
]

urlpatterns += [
    path('accounts/signup/', views.signup, name='signup'),
    path('signup/', views.signup_sidebar, name='signup_sidebar'),
    path('user/myprofile_detail/<int:pk>/', views.UserProfileListView.as_view(), name='profile_detail'),
    path('user/myprofile_edit/', views.update_profile, name='user_top_update'),
    path('password/', views.change_password, name='change_password'),
]

urlpatterns += [
    path('management/user/', views.UserListView.as_view(), name='user_list'),
    path('management/user-delete/<int:pk>/', views.UserDelete.as_view(), name='user-delete'),
    path('search/user/', views.SearchUserView.as_view(), name='search_user'),
    path('management/user-update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    path('management/user-update/profile/<int:pk>/', views.UsersSidebarProfilesUpdate.as_view(), name='users_profiles_update_sidebar'),
    path('users_update_profiles_view/<id>/', views.users_update_profiles_view, name='update_profiles_view'),
    path('profiles_detail_view/<id>/', views.profiles_detail_view, name='profiles_detail_view'),
    ##  permission #####
    path('management/user-add-permissions/<int:pk>/', views.UserAddPermissionUpdate.as_view(), name='add-permissions'),
    path('management/user-permissions/', views.UserListPermissionsView.as_view(), name='permissions'),
    ## group ##
     path('management/user-group/', views.CreateUserGroup.as_view(), name='user-group'),
     path('management/user-group-list/', views.UserGroupListView.as_view(), name='user_group_list'),
     path('management/user-group/update/<int:pk>/', views.UserGroupUpdate.as_view(), name='user_group_update'),
     path('management/user-group-delete/<int:pk>/', views.UserGroupDelete.as_view(), name='user-group-delete'),
]

urlpatterns += [
    path('wip/production-flow/test-station', views.SerialNumberTestForm.as_view(), name='production_flow_station'),
    path('tool_box/workorder_list', views.WorkOrderListView.as_view(), name='workorder_list'),
    path('tool_box/workorder_list_reverse', views.WorkOrderReverseListView.as_view(), name='workorder_list_reverse'),
    path('tool_box/workorder-detail/<int:pk>',views.WorkOrderDetailDetailView.as_view(), name='workorder-detail'),
    path('tool_box/workordermanager-wo-detail/<pk>', views.workorder_detail, name='workordermanager-wo-detail'),
    path('tool_box/workordermanager-sn-detail/<pk>', views.serialnumber_detail, name='workordermanager-sn-detail'),
    path('tool_box/workorder_list/status/<pk>/', views. WorkOrderEditUpdate.as_view(), name='workorder-status'),
    path('tool_box/label-center', views.label_center, name='label-center'),
    path('tool_box/search_by_sn', views.SearchResultsBySNView.as_view(), name='search_by_sn'),
    path('tool_box/search_by_wo', views.SearchResultsByWOView.as_view(), name='search_by_wo'),
    path('tool_box/label_create', views.label_create, name='label-create'),
    path('tool_box/serialnumber_list', views.SerialNumberListView.as_view(), name='serialnumber_list'),
    path('tool_box/serialnumber_list/edit/', views.serialnumber_update, name='serialnumber_update'),
    path('tool_box/serialnumber_detail/<str:pk>/', views.SNManagereDetail.as_view(), name='serialnumber_detail'),

    path('wip/serialnumber/detail/', views.SerialNumberDetail.as_view(), name='serialnumber-detail'),
    path('modalform/workorder/', views.WorkOrderIndex.as_view(), name='index-workorder'),
    path('wip/forms/last_button/', views.post_generate_sn, name='last_button'),
    path('master-list/', views.MaterialMasterListView.as_view(), name='master_list'),

]

urlpatterns += [
    path('tool_box/hold_station', views.hold_station, name='hold_station'),
    path('tool_box/UnHold/<str:hold_id>/', views.UnHold, name='UnHold'),
    path('tool_box/HoldEdit/<str:hold_id>/', views.HoldEdit, name='HoldEdit'),
    path('tool_box/HoldAdd', views.HoldAdd, name='HoldAdd'),
]

sfc/maskconfig/urls.py
from django.urls import path
from . import views

app_name = 'maskconfig'

urlpatterns = [
    path('', views.MaskConfigListView.as_view(), name='home'),
    path('segments/', views.segment, name='segments'),
    path('segments/create', views.createsegment, name='create-segment'),
    path('segments/delete/<int:pk>/', views.DeleteSegment.as_view(), name='delete-segment'),
    path('segments/edit', views.edit_segment, name='edit-segment'),
    # path('create/', views.CreateMask.as_view(), name='create-mask'),
    path('create/', views.createmask, name='create-mask'),

]


urlpatterns += [
    path('row/create/', views.createmask_row, name='create-mask-row'),
    path('segments/row/create', views.createsegment_row, name='create-segment-row'),
    path('row/delete/<int:pk>/', views.MaskDelete.as_view(), name='delete-mask-row'),
    path('row/edit/<int:pk>/', views.MaskUpdate.as_view(), name='update-mask-row'),
    path('row/detail/<int:pk>/', views.MaskDetailView.as_view(), name='detail-mask-row'),
    path('row/segment/create', views.CreateSegment.as_view(), name='create-segment-row'),
    path('list', views.MaskConfigListView.as_view(), name='mask-list'),
    path('segments/list/', views.segment_template, name='segment-list'),
    path('reverse', views.MaskConfigListReverseView.as_view(), name='mask-list-reverse'),
    path('row/segment/edit/<int:pk>/', views.MaskSegmentUpdate.as_view(), name='update-masksegment-row'),
    path('list/segment/update/', views.SegmentListUpdate.as_view(), name='update-masksegment-list'),
    path('row/segment/update/<int:pk>/', views.MaskSegmentModalUpdate.as_view(), name='update-masksegment-modal'),
    path('row/segment/modal/update/', views.mask_modal_row, name='update-masksegment-modal-row'),
    path('mask/create/', views.MaterialMasterListView.as_view(), name='mask-create'),
    path('maskmanager/create/', views.MaskConfigCreateView.as_view(), name='maskmanager-create'),

    # ##### ooba ######
    path('ooba/list/', views.ooba_list_view, name='ooba_list'),
    path('ooba/create/', views.ooba_create_view, name='ooba_create'),


]

sfc/qms/urls.py
from django.urls import path
from .views import *

app_name = 'qms'

urlpatterns = [
    # path('', views.QMSHomeView.as_view(), name='home'),
    path('inspection-tool/', InspectionListView.as_view(), name='inspection-tool'),
    path('inspection-tool/create', CreateInspectionToolView.as_view(), name='inspection-tool-create'),
    path('inspection-tool/update/<str:pk>/', UpdateInspectionToolView.as_view(), name='inspection-tool-update'),
    path('inspection-level/', InspectionLevelListView.as_view(), name='inspection-level'),
    path('inspection-level/create', CreateInspectionLevelView.as_view(), name='inspection-level-create'),
    path('inspection-level/update/<str:pk>/', UpdateInspectionLevelView.as_view(), name='inspection-level-update'),
    path('inspection-free/', MaterialInspectionFreeListView.as_view(), name='inspection-free'),
    path('inspection-free/create', CreateMaterialInspectionFreeView.as_view(), name='inspection-free-create'),
    path('inspection-free/update/<str:pk>/', UpdateMaterialInspectionFreeView.as_view(), name='inspection-free-update'),

    ############################
    path('inspection_manufacture_info/', views.ManufactureInfo.as_view(), name='inspection_manufacture_info'),
    path('inspection_mrb/', views.MRBauditInfo.as_view(), name='inspection_mrb'),
    path('inspection_waiting/', views.WaitingList.as_view(), name='inspection_waiting'),
    path('inspection_waiting/delete/<str:pk>/', views.WaitingListDelete.as_view(), name='waiting-list-delete'),



    # #### template only #######
    path('inspection/', views.inspection, name='inspection'),
    path('wms_receiving_form/', views.wms_receiving_form, name='wms_receiving_form'),

]

sfc/sfc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import path

from django.contrib.auth import views as auth_views





urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('manufacturing/', include('manufacturing.urls')),
    path('config/git', include('git.urls')),
    path('config/', include('maskconfig.urls',namespace='maskconfig')),
    path('line/', include('line.urls')),
    path('line/', include('rules.urls')),
    path('api/', include('api.urls')),
    path('offline_station/', include('offline_station.urls')),
    path('shipping/', include('shipping.urls')),
    path('qms/', include('qms.urls')),
    path('wms/', include('wms.urls')),
    
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='manufacturing/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.urls import reverse_lazy
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('password_reset/', auth_views.password_reset, name='password_reset'),
    # path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]


urlpatterns += [

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_formIMS.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_doneIMS.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirmIMS.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_completeIMS.html'
         ),
         name='password_reset_complete'),
]


sfc/qms/templates/inspection_waiting/inspection_waiting.html
{% include 'manufacturing/include/header-qms.html' %}
{% load static %}
<link href="{% static 'css/qms.css' %}" rel="stylesheet">
{% include 'manufacturing/include/sidebar.html' %}
{% include 'manufacturing/include/error-modal-style.html' %}
<section id="main-content" class="login-wrap">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <ol class="breadcrumb">
              <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Dashboard</a></li>
              <!--<li><i class="icon_cogs"></i><a href="{% url 'manufacturing:sub_config' %}">Configuration</a></li>-->
              <li><i class="fa fa-th-list"></i>Inspection Waiting List</li>
            </ol>
          </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <div class="whole whole-table">
                         <div class="main-content">
                            <div class="nav-user-search  clearfix header-search-box">
                                <div class="nav top-menu top-button">
                                     <form  class="navbar-form" id="search" action="" method="get">
                                      <div class="nav search-row list-title-search" id="top_menu">
                                        <div><input name="q" class="form-control" type="text" placeholder=" Search"></div>
                                               <div style="width: 30px;">
                                                   <button class="nav-user-search-icon" type="submit" style="padding: 0;">
                                                       <i _ngcontent-crw-c2="" style="font-size: 3rem;" class="icon_search-2 search-icon text-muted i-Magnifi-Glass1"></i>
                                                   </button>
                                               </div>
                                         </div>
                                     </form>
                                </div>

                            </div>
                         </div>
                        {% include 'inspection_waiting/inspection_waiting_detail.html' %}
                    </div>
                 </section>
              </div>
            </div>
          </div>
      </section>
</section>
{% include 'manufacturing/include/javascript-sidebar.html' %}
{% load static %}
<script src="{% static 'js/manufacturing/tab.js' %}"></script>
<script src="{% static 'js/QMS/inspection.js' %}"></script>




sfc/qms/templates/inspection_waiting/inspection_waiting_detail.html
{% load static %}
<link href="{% static 'css/qms.css' %}" rel="stylesheet">

<div id="maxheight">

      <table class="table table-striped table-advance table-hover table-flex table-margin">
          <tbody>
            <tr id="table-header" class = "column table-header">

                <th> <button class="icon-text"> <a href="{% url 'maskconfig:home' %}">&#8595; </a> <span>Order</span></button></th>
                 <th></th>
                 <th ><i class="icon_grid-3x3"></i> &nbsp; Form Code</th>
                 <th ><i class="icon_profile"></i> &nbsp; Model</th>
                 <th><i class="icon_check"></i> &nbsp; Inspected</th>
                 <th><i class="icon_cogs"></i>&nbsp; Material Qty</th>
                <th><i class="icon_cogs"></i>&nbsp; Status</th>
                <th><i class="icon_cogs"></i>&nbsp; Action</th>
                 <th>&nbsp;</th>
            </tr>
          </tbody>
            {% if waiting_list %}
             {% for waiting in waiting_list %}
            <tr class="column">
                      <th><p>&nbsp;&nbsp;{{ forloop.counter }}</p></th>

                        <iframe name="formDestination" style="display: none;"></iframe>
                        <form action="" method="post" enctype="multipart/form-data" target="formDestination">
                            <th><input type="hidden" name="chk"/>&nbsp;&nbsp;</th>
                            <th class="column-action">{{ waiting.incoming_list_id }}</th>
                            <th class=""> <p>{{ waiting.model_id }}</p></th>
                            {% if waiting.inspected == 0 %}
                            <th class=""><p>Not Inspected</p></th>
                            {% elif waiting.inspected == 1 %}
                            <th class=""><p>Inspected</p></th>
                            {% endif %}
                             <th class=""><p>{{ waiting.material_qty}}</p></th>
                            {% if inspection_list %}
                            {% for inspection in inspection_list %}
                            {% ifequal waiting.pk inspection.pk %}
                            {% if inspection.status == 0 %}
                             <th><p>Waiting</p></th>
                            {% else %}
                            <th><p>Completed</p></th>
                            {% endif %}{% endifequal %}{% endfor %}{% endif %}
                             <th class="column-action">
                         </form>
                         <div class="mask-ul" style="display: flex; justify-content: center;">
                             <div>
                                {% if inspection_list %}
                                {% for inspection in inspection_list %}
                                {% ifequal waiting.pk inspection.pk %}
                                {% if inspection.status == 0 %}
                              <div class="icon-text">
                                 <img style="width: 22px; margin-left: 3px;" src="{% static 'svg/exclamation.svg' %}" alt="icon">
                                <span style="text-align: center; font-weight: 400;">Waiting</span></div>
                              {% else %}

                              <form onsubmit="return confirm('Confirm delete?');" action="{% url 'qms:waiting-list-delete' waiting.incoming_list_id %}" method="post" style="display: inline;">
                              {% csrf_token %}
                              <button class="icon-text">
                                 <img style="width: 22px; margin-left: 3px;" src="{% static 'svg/delete.svg' %}" alt="icon">
                                <span>Completed</span></button></form>
                              {% endif %}{% endifequal %}{% endfor %}{% endif %}
                          </div>
                         </div>
                   </th>
                   <th>&nbsp;</th>
            </tr>
           {% endfor %}
            {% endif %}

              <table  class="table table-striped table-advance table-hover table-flex">
                <tbody>
                   <div class = "column">
                        <!-- ############## page  ############## -->
                        {% include 'manufacturing/include/pagination.html' %}
                        <!-- #################### end page #########   -->
                   </div>
                 </tbody>
            </table>
        <form id="hi" action="/config" method="POST"></form>
        </div>
{% load static %}
<script src="{% static 'js/line/warning-modal.js' %}"></script>
<script src="{% static 'js/manufacturing/inline.js' %}"></script>



