sfc/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('checkssn', views.checkssn, name='checkssn'),
    path('scankeypart', views.scankeypart, name='scankeypart'),
    path('testssn', views.testssn, name='testssn'),
    path('checkkeypart', views.checkkeypart, name='checkkeypart'),
    path('getpart', views.getpart, name='getpart'),
    path('get-delivery-number', views.getDeliveryNumber, name = 'getDeliveryNumber'),

]   

sfc/line/urls.py
from django.urls import path
from . import views

app_name = 'line'

urlpatterns = [

    path('route/stations/', views.station_route, name='stations'),
    path('route/stations/create', views.stationroute_create, name='create-sationroute'),
    path('route/stations/edit', views.stationroute_edit, name='station-route-edit'),
    path('stations/', views.all_stations, name='all-stations'),
    path('station/create', views.station_config, name='create-station'),
    path('station/edit/<str:station_id>/', views.station_edit, name='edit-station'),
    path('', views.wip_search, name='wip'),
    path('wip/', views.station_list, name='station-list'),
    path('route/', views.route_list, name='route'),
    path('route/create/', views.route_config, name='create-route'),
    path('wip/workflow/', views.wip_flow, name='flow'),
    path('wip/check-in/', views.check_in, name='check-in'),
    path('config/pack/', views.pack_config, name='pack'),
    path('config/pack/create/', views.create_pack_config, name='create-pack'),
    # path('config/pallet/', views.pallet_config, name='pallet'),
    # path('config/pallet/create/', views.create_pallet_config, name='create-pallet'),

    path('wip/repair/', views.RepairStationDetailView.as_view(), name='repair_station'),
    # path('wip/repair/result_update/<str:pk>/', views.TestingResultUpdate.as_view(), name='result_update'),
    # path('wip/repair_code/', views.RepairCodelView.as_view(), name='repair_code'),
    path('wip/workflow/replace-part', views.replace_part, name='replace-part'),
    path('wip/repair_update/', views.update_repair, name='update_repair'),
####### tool box #########
    # path('tool_box/state_list', views.StateListView.as_view(), name='state_list'),
    # path('tool_box/state_list/delete/<int:pk>/', views.StateDelete.as_view(), name='state_delete'),
    # path('tool_box/state_list/add_state/', views.StateAdd.as_view(), name='add_state'),
    # path('tool_box/state_list/edit/<int:pk>/', views.StateUpdate.as_view(), name='update_state_row'),

####### config ###########


]

sfc/manufacturing/urls.py
from django.urls import path
from . import views

app_name = 'manufacturing'
urlpatterns = [
    path('', views.home, name='home'),
    path('reset_confirm/', views.reset_confirm, name='reset_confirm'),

    path('label_center/', views.label_center, name='label_center'),
    path('label_center/get-serial-numbers', views.get_serial_numbers, name='get-sns-by-wo'),
    path('so_list/', views.so_list, name='so_list'),
    path('serialnumber_log/', views.serialnumber_log, name='serialnumber_log'),

# sidebar tabs ###########
    path('sidebar/sub_config/', views.sub_config, name='sub_config'),
    path('sidebar/sub_toolbox/', views.sub_toolbox, name='sub_toolbox'),
    path('sidebar/sub_wip/', views.sub_wip, name='sub_wip'),
    path('sidebar/sub_shipping_manager/', views.sub_shipping_manager, name='sub_shipping_manager'),
    path('sidebar/sub_qms/', views.sub_qms, name='sub_qms'),
    path('sidebar/sub_wms/', views.sub_wms, name='sub_wms'),

#### user profile ###############
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('add_profile/', views.user_add_profile, name='add_profile'),
    path('users/add_profiles/', views.UsersProfilesAdd.as_view(), name='users_add_profiles'),
    path('users/profiles_list/', views.UsersProfilesListView.as_view(), name='users_profiles_list'),
    path('users/profiles_delete/<int:pk>/', views.UsersProfilesDelete.as_view(), name='users_profile_delete'),
    path('users/profiles_update/<int:pk>/', views.UsersProfilesUpdate.as_view(), name='users_profiles_update'),
]

urlpatterns += [
    path('accounts/signup/', views.signup, name='signup'),
    path('signup/', views.signup_sidebar, name='signup_sidebar'),
    path('user/myprofile_detail/<int:pk>/', views.UserProfileListView.as_view(), name='profile_detail'),
    path('user/myprofile_edit/', views.update_profile, name='user_top_update'),
    path('password/', views.change_password, name='change_password'),
]

urlpatterns += [
    path('management/user/', views.UserListView.as_view(), name='user_list'),
    path('management/user-delete/<int:pk>/', views.UserDelete.as_view(), name='user-delete'),
    path('search/user/', views.SearchUserView.as_view(), name='search_user'),
    path('management/user-update/<int:pk>/', views.UserUpdate.as_view(), name='user-update'),
    path('management/user-update/profile/<int:pk>/', views.UsersSidebarProfilesUpdate.as_view(), name='users_profiles_update_sidebar'),
    path('users_update_profiles_view/<id>/', views.users_update_profiles_view, name='update_profiles_view'),
    path('profiles_detail_view/<id>/', views.profiles_detail_view, name='profiles_detail_view'),
    ##  permission #####
    path('management/user-add-permissions/<int:pk>/', views.UserAddPermissionUpdate.as_view(), name='add-permissions'),
    path('management/user-permissions/', views.UserListPermissionsView.as_view(), name='permissions'),
    ## group ##
     path('management/user-group/', views.CreateUserGroup.as_view(), name='user-group'),
     path('management/user-group-list/', views.UserGroupListView.as_view(), name='user_group_list'),
     path('management/user-group/update/<int:pk>/', views.UserGroupUpdate.as_view(), name='user_group_update'),
     path('management/user-group-delete/<int:pk>/', views.UserGroupDelete.as_view(), name='user-group-delete'),
]

urlpatterns += [
    path('wip/production-flow/test-station', views.SerialNumberTestForm.as_view(), name='production_flow_station'),
    path('tool_box/workorder_list', views.WorkOrderListView.as_view(), name='workorder_list'),
    path('tool_box/workorder_list_reverse', views.WorkOrderReverseListView.as_view(), name='workorder_list_reverse'),
    path('tool_box/workorder-detail/<int:pk>',views.WorkOrderDetailDetailView.as_view(), name='workorder-detail'),
    path('tool_box/workordermanager-wo-detail/<pk>', views.workorder_detail, name='workordermanager-wo-detail'),
    path('tool_box/workordermanager-sn-detail/<pk>', views.serialnumber_detail, name='workordermanager-sn-detail'),
    path('tool_box/workorder_list/status/<pk>/', views. WorkOrderEditUpdate.as_view(), name='workorder-status'),
    path('tool_box/label-center', views.label_center, name='label-center'),
    path('tool_box/search_by_sn', views.SearchResultsBySNView.as_view(), name='search_by_sn'),
    path('tool_box/search_by_wo', views.SearchResultsByWOView.as_view(), name='search_by_wo'),
    path('tool_box/label_create', views.label_create, name='label-create'),
    path('tool_box/serialnumber_list', views.SerialNumberListView.as_view(), name='serialnumber_list'),
    path('tool_box/serialnumber_list/edit/', views.serialnumber_update, name='serialnumber_update'),
    path('tool_box/serialnumber_detail/<str:pk>/', views.SNManagereDetail.as_view(), name='serialnumber_detail'),

    path('wip/serialnumber/detail/', views.SerialNumberDetail.as_view(), name='serialnumber-detail'),
    path('modalform/workorder/', views.WorkOrderIndex.as_view(), name='index-workorder'),
    path('wip/forms/last_button/', views.post_generate_sn, name='last_button'),
    path('master-list/', views.MaterialMasterListView.as_view(), name='master_list'),

]

urlpatterns += [
    path('tool_box/hold_station', views.hold_station, name='hold_station'),
    path('tool_box/UnHold/<str:hold_id>/', views.UnHold, name='UnHold'),
    path('tool_box/HoldEdit/<str:hold_id>/', views.HoldEdit, name='HoldEdit'),
    path('tool_box/HoldAdd', views.HoldAdd, name='HoldAdd'),
]

sfc/sfc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import path

from django.contrib.auth import views as auth_views





urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('manufacturing/', include('manufacturing.urls')),
    path('config/git', include('git.urls')),
    path('config/', include('maskconfig.urls',namespace='maskconfig')),
    path('line/', include('line.urls')),
    path('line/', include('rules.urls')),
    path('api/', include('api.urls')),
    path('offline_station/', include('offline_station.urls')),
    path('shipping/', include('shipping.urls')),
    path('qms/', include('qms.urls')),
    path('wms/', include('wms.urls')),
    
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='manufacturing/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.urls import reverse_lazy
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('password_reset/', auth_views.password_reset, name='password_reset'),
    # path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]


urlpatterns += [

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_formIMS.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_doneIMS.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirmIMS.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_completeIMS.html'
         ),
         name='password_reset_complete'),
]


sfc/shipping/urls.py
from django.urls import path
from . import views

app_name = 'shipping'

urlpatterns = [
    ######################### palletization #############################################
    path('wip/palletize/', views.PalletStationDetailView.as_view(), name='pallet_station'),
    path('wip/palletize/add_sn/', views.add_sn_view, name='pallet_add_sn'),
    path('wip/palletize/delete/<str:pk>/', views.PalletDetail.as_view(), name='pallet_detail_delete'),
    path('wip/palletize/delete/<str:pk>', views.delete_sn_view, name='delete_sn'),
    path('wip/palletize/save_dimension/', views.save_dimension, name='save_dimension'),
    path('wip/palletize/save_dimension/<str:pk>/', views.PalletDetail.as_view(), name='after_save_dimensions'),
    path('wip/palletize/create_new_pallet/', views.create_new_pallet, name='create_new_pallet'),
    path('wip/palletize/create_new_pallet/<str:pk>/', views.PalletDetail.as_view(), name='after_create_new'),

    path('wip/palletize/validate-sn/', views.validate_sn_json, name='validate_sn_json'),
    path('wip/palletize/delete-sn/', views.delete_sn_json, name='delete_sn_json'),
    path('wip/palletize/add-sn/', views.add_sn_json, name='add_sn_json'),

    path('wip/palletize/add/', views.add_sn_test_view, name='add_sn_to_pallet'),
    path('wip/palletize/add/<str:pk>', views.PalletDetail.as_view(), name='pallet_detail'),
    path('wip/palletize/create_new_pallet_id/', views.create_pallet_id, name='create_new_pallet_id'),
   # path('wip/palletize/create_new_pallet_id/<str:pk>/', views.PalletDetail.as_view(), name='after_create_new_id'),

    # #######################  ship out ###########################################
    path('wip/ship_out/', views.SalesOrderEnterView.as_view(), name='ship_out_station'),
    path('wip/ship_out/success/', views.SalesOrderSuccessView.as_view(), name='ship_out_success'),
    path('wip/ship_out/detail/<str:pk>/', views.SalesDetail.as_view(), name='ship_out_detail'),
    path('wip/shipout/process/', views.Process, name='process'),
    path('wip/shipout/validate_sn/', views.ValidateSN, name='validate_sn'),
    path('wip/shipout/validate_sku/', views.ValidateSKU, name='validate_sku'),

    # ####################### truck load #############################################
    path('wip/truckload/', views.TruckLoadView.as_view(), name='truckload_station'),
    path('wip/truckload/getpallet/', views.get_pallets_by_dn, name='get_pallet'),
    path('wip/truckload/savetruckload/', views.SaveTruckLoad, name='save_truck'),

    # ####################### salesorder #############################################
    path('tool_box/salesorder_list/', views.SalesOrderListView.as_view(), name='salesorder_list'),
    path('tool_box/salesorder_list/detail/<int:pk>/', views.SalesOrderDetailView.as_view(), name='salesorder_detail'),

    # ####################### deliverynumber #############################################
    path('tool_box/deliverynumber_list/', views.DeliveryNumberListView.as_view(), name='deliverynumber_list'),
    path('tool_box/deliverynumber_list/detail/<str:pk>/', views.DeliveryNumberDetailView.as_view(), name='deliverynumber_detail'),


    path('wip/unpalletize/', views.UNPalletStationDetailView.as_view(), name='unpallet_station'),
    path('wip/unpalletize/detail/<str:pk>', views.UNPalletDetail.as_view(), name='unpallet_detail'),


    path('pallet-printer', views.PalletTemplateForm.as_view(), name="print_pallet_list"),


    ]

sfc/line/forms.py
from django import forms
from .models import Route, Station
from django.apps import apps

class RouteForm(forms.Form):
    route_id = forms.CharField(max_length=20,
                            widget=forms.TextInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Name...'
                                                          }))
    MaterialMaster = apps.get_model('manufacturing','MaterialMaster')
    

    model = forms.ModelChoiceField(queryset=MaterialMaster.objects.all())


    plantcode = forms.CharField(max_length=20,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Plant Code...'
                                                              }))
    first_station = forms.ModelChoiceField(queryset=Station.objects.all())


class RouteSearchForm(forms.Form):
    ver = forms.CharField(max_length=20,
                            widget=forms.TextInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Ver...'
                                                          }))


class PackForm(forms.Form):
    workorder_type = forms.CharField(max_length=20,
                                     widget=forms.TextInput(attrs={'class': 'form-control',
                                                                   'placeholder': 'WorkOrder Type...'
                                                                   }))
    options = forms.MultipleChoiceField(choices=[(1, 'Label'), ('2', 'Country Kit')],
                                        widget=forms.CheckboxSelectMultiple(attrs={'class': 'radio-button-forms'
                                                                                   }))


class PalletForm(forms.Form):
    workorder_type = forms.CharField(max_length=20,
                                     widget=forms.TextInput(attrs={'class': 'form-control',
                                                                   'placeholder': 'WorkOrder Type...'
                                                                   }))
    pallet_limit = forms.IntegerField()
    options = forms.MultipleChoiceField(choices=[(1, 'pallet mix')],
                                        widget=forms.CheckboxSelectMultiple(attrs={'class': 'radio-button-forms'
                                                                                   }))

sfc/line/templates/production/palletize/palletize-create-pallet.html
<div class="modal" id="generated" role="dialog">
     <div class="row whole whole-status modal-content-detail modal-p">
          <p> Create a new pallet?</p>
          <div class="modal-button-container">
             <form name="create" class="form-horizontal modal-scanner-version" action="{% url 'shipping:create_new_pallet' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex-button">

                    <button class="nav-user-search-icon btn btn-error modal-button-red" type="submit" data-dismiss="modal">Cancel</button>
                    <button class="nav-user-search-icon btn btn-primary modal-button-blue" type="submit">Confirm</button>
                </div>
                <input class="form-control col-sm-12" type="hidden" name="pallet_id" value="" id="create_new_pallet">
                <input type="hidden" name="updater" id="updater_input" class="form-control" value="{{ user.get_username }}">
                <input type="hidden" name="creator" id="creator" class="form-control" value="{{ user.get_username }}">
                 {% for pallet in pallet_list %}
                 {% if forloop.last %}
                 <input type="hidden" name="last_pallet_id" id="last_pallet_id" class="form-control" value="{{ pallet.pallet_id }}">
                 {% endif %}
                 {% empty %}
                 <input type="hidden" name="last_pallet_id" id="last_pallet_id" class="form-control" value="P_00000">
                 {% endfor %}
             </form>
          </div>
     </div>
</div>





sfc/line/templates/production/palletize/palletize-js.html
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
$(document).ready(function(){
  var textbox = $("#textbox1");
  textbox.change(function() {
     $("#table1").find("td").each(function(){
        if($(this).html()==textbox.val()){
           alert(textbox.val());
        };
     })
  });
});
</script>
<script>
var tds;
$('tr').each(function(i, item){
    tds = $(this).find('td');
    tds.each(function(j, elem1){
        tds.each(function(k, elem2){
            if($(elem1)[0] != $(elem2)[0] && $(elem1).text() == $(elem2).text()){
                $(elem1).addClass('cl');
            }
        });
    });
});
</script>
<script>
 $(document).ready(function() {
    var tableRows = $("#sortable tbody tr"),
        // we know exactly how large to make it, so don't use []
        htmlStrings = new Array(tableRows.length),
        i, j, current, comparing;

    for (i = 0; i < tableRows.length; i++) {
        current = htmlStrings[i];
        // get each innerHTML just once
        if (!current) {
            current = {
                html: tableRows.get(i).innerHTML,
                isDup: false
            };
            htmlStrings[i] = current;
        }

        // if we already know it's a dup, so we're done
        if (current.isDup) { continue; }

        // start j at i+1 since we've already looked at the previous i rows
        for (j = i + 1; j < tableRows.length; j++) {
            // could stay DRY and put this into a function;
            // doing so may decrease performance (not benchmarked)
            comparing = htmlStrings[j];
            if (!comparing) {
                comparing = {
                    html: tableRows.get(j).innerHTML,
                    isDup: false
                };
                htmlStrings[j] = comparing;
            }

            if (comparing.isDup) { continue; }

            // It comes to this: we must actually compare now.
            if (current.html === comparing.html) {
                current.isDup = true;
                comparing.isDup = true;

                // mark it
                tableRows.eq(j).css('backgroundColor', '#a5bff4');
            }
        }

        if (current.isDup) {
            // mark it
            tableRows.eq(i).css('backgroundColor', '#a5bff4');
        }

    }
});
</script>

sfc/line/templates/production/palletize/palletize.html
{% include 'manufacturing/include/header.html' %}
{% include 'manufacturing/include/error-modal-style.html' %}
{% load static %}
<link href="{% static 'css/pallet.css' %}" rel="stylesheet">
<link href="{% static 'css/permission/style.css' %}" rel="stylesheet">
<link href="{% static 'css/dist/jquery.tree-multiselect.min.css' %}" rel="stylesheet">
<script src="{% static 'js/vendor/jquery-1.11.3.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/manufacturing/jquery.tree-multiselect.js' %}"></script>
{% include 'manufacturing/include/sidebar.html' %}
{% include 'manufacturing/include/error-modal-style.html' %}
<section id="main-content">
  <section class="wrapper">
    <div class="row">
      <div class="col-lg-12">
        <ol class="breadcrumb">
            <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Dashboard</a></li>
            <!--<li><i class="icon_genius"></i><a href="{% url 'manufacturing:sub_wip' %}">WIP Management</a></li>-->
            <!--<li><i class="icon_genius"></i><a href="{% url 'manufacturing:sub_shipping_manager' %}">Shipping Management</a></li>-->
            <li><i class="fa fa-square-o"></i>Palletization</li>
        </ol>
      </div>
    </div>

      <div class="row">
        <div class="col-lg-12">
          <section class="panel">
            <div class="panel-body" style="padding-bottom: 5rem;">
                     <div class="form-horizontal mobile-content-pallet">
                            <div class="form-group section-border">
                              <div class="col-sm-6 scanner-content">
                                    <div class="col-sm-12" id="open-available-pallet" style="padding: 0;">
<!--                                        <div class="col-sm-6 padding-left-0" id="create-button-div">-->
<!--                                            <button data-toggle="modal" data-target="#generated" class="btn btn-close action-header-button" id="open_input" type="submit" style="float:left; mergin-left: 0; padding: 0;" onclick="ShowNew()">Create New</button>-->
<!--                                        </div>-->
                                         <div id="create_pallet_id" class="col-sm-12 padding-left-0" style="padding: 0;">
                                           <div class="col-sm-6 padding-left-0">
                                            <button class="btn btn-open header-button padding-left-0"  type="submit" style="float:left; mergin-left: 0; display: none;" onclick="ShowNew()">Back to List1</button>
                                           </div>
                                        </div>
                                        <div class="col-sm-6 padding-left-0" style="display: none;">
                                            <button class="btn btn-open header-button padding-left-0" id="close-pallet" onclick="ShowDimensions()" style="float:left; mergin-left: 0;display:none;">Close</button>
                                        </div>
                                    </div>
                                   {% include 'production/palletize/palletize-create-pallet.html' %}
                                   <section class="panel">
                                       <div class="col-sm-12 scanner-content">
                                             <div class="form-group section-border">
                                                  <div class="scanner-content" >
                                                 <h2 class="pallettization-title main-pallet-list" style="margin-left: 15px">Pallet List</h2>
                                                  <button data-toggle="modal" data-target="#generated" class="btn btn-info pallet-header-button" id="open_input" type="submit" style="float:left; mergin-left: 0; padding: 0;" onclick="ShowNew()">Create a new pallet</button>
                                                  </div>
                                             </div>
                                       </div>
                                        <div id="open-pallet">
                                        {% include 'production/palletize/palletize_open_only_pallet.html' %}
                                        </div>
                                   </section>
                                </div>
                                 <div class="col-sm-6 scanner-content">
                                    <section class="panel">
<!--                                     <div class="col-sm-12" style="padding: 0;">-->
<!--                                      <div class="form-group">-->
                                         <div class="col-sm-12 scanner-content">
                                                    <h2 class="pallettization-title">Pallet Detail</h2>
                                                  <div class="form-group section-border disable-add-sn" style="margin-top: 26px;">
                                                   <!--  add sn to pallet -->
                                                   <div class="form-horizontal"  id="search" action="{% url 'shipping:add_sn_to_pallet' %}" method="POST" enctype="multipart/form-data">
                                                       <div class="col-sm-12">
                                                           <div class="icon-text" >
                                                               <div class="" style="margin:0; width:100%;">
                                                                   <div id="repaircode" class="form-control form-control-replacement" type="text" placeholder="">Please select a pallet.</div>
                                                               </div>
                                                                <input type="hidden" name="current_qty" class="form-control" value="{{ pallet.current_qty }}">
        <!--                                                                                                <input type="hidden" name="model" class="form-control" value="{{ pallet.model }}">-->
                                                                <input type="hidden" name="updater" class="form-control" value="{{ user.get_username }}">
                                                               {% include 'production/palletize/palletize_hidden_input.html' %}
                                                            </div>
                                                       </div>

                                                      <div class="col-sm-5 icon-text " style="padding-left:0; display: none;">
                                                        <div class="btn btn-info header-button col-sm-12" id="sn-button-main" style="margin: 0;float: left; cursor: none;"><strong>&#x271A;&nbsp;Serial Number</strong></div>
                                                          <span class="span-pallet-sn"><button class="icon-text"><img style="width: 22px; margin-left: 3px;"
                                                               src="{% static 'svg/delete.svg' %}" alt="icon"></button>Please select a pallet.
                                                          </span>
                                                     </div>
                                                 </div>
                                            <!--  end add sn to a pallet -->
                                            </div>
                                         </div>
                                          <div class="">
                                                {% if messages %}
                                                    {% for message in messages %}
                                                         <div id="myModal" class="modal-log message-box-bottom" style="padding-top: 0; z-index: 100;">
                                                              {% if message.tags %}
                                                             <div class="modal-content-{{ message.tags }}">
                                                                 {% endif %}
                                                                 <span class="close" data-dismiss="modal" style="z-index: 100;">×</span>
                                                                  <div class="warning-modal-body">
                                                                     <p>{{ message }}</p>
                                                                   </div>
                                                               </div>
                                                            <button style="display: none;" id="myBtn">Open Modal</button>
                                                         </div>
                                                    {% endfor %}
                                                {% endif %}
                                          </div>
<!--                                    </div>-->
                                        {% include 'production/palletize/palletize_detail_tabs.html' %}
<!--                                    </div>-->
                                  </section>
                                </div>
                            </div>
                        </div>
                   </div>
             </section>
         </div>
    </div>
 </section>
</section>
{% load static %}
<script src="{% static 'js/line/warning-modal.js' %}"></script>
<script src="{% static 'js/pallet/pallet.js' %}"></script>
<link href="{% static 'css/mobile-version.css' %}" rel="stylesheet">
{% include 'manufacturing/include/javascript-for-permission.html' %}
</body>
</html>