sfc/api/urls.py
from django.urls import path, include
from . import views

app_name = 'api'

urlpatterns = [
    path('checkssn', views.checkssn, name='checkssn'),
    path('scankeypart', views.scankeypart, name='scankeypart'),
    path('testssn', views.testssn, name='testssn'),
    path('checkkeypart', views.checkkeypart, name='checkkeypart'),
    path('getpart', views.getpart, name='getpart'),
    path('get-delivery-number', views.getDeliveryNumber, name = 'getDeliveryNumber'),

]   

sfc/maskconfig/urls.py
from django.urls import path
from . import views

app_name = 'maskconfig'

urlpatterns = [
    path('', views.MaskConfigListView.as_view(), name='home'),
    path('segments/', views.segment, name='segments'),
    path('segments/create', views.createsegment, name='create-segment'),
    path('segments/delete/<int:pk>/', views.DeleteSegment.as_view(), name='delete-segment'),
    path('segments/edit', views.edit_segment, name='edit-segment'),
    # path('create/', views.CreateMask.as_view(), name='create-mask'),
    path('create/', views.createmask, name='create-mask'),

]


urlpatterns += [
    path('row/create/', views.createmask_row, name='create-mask-row'),
    path('segments/row/create', views.createsegment_row, name='create-segment-row'),
    path('row/delete/<int:pk>/', views.MaskDelete.as_view(), name='delete-mask-row'),
    path('row/edit/<int:pk>/', views.MaskUpdate.as_view(), name='update-mask-row'),
    path('row/detail/<int:pk>/', views.MaskDetailView.as_view(), name='detail-mask-row'),
    path('row/segment/create', views.CreateSegment.as_view(), name='create-segment-row'),
    path('list', views.MaskConfigListView.as_view(), name='mask-list'),
    path('segments/list/', views.segment_template, name='segment-list'),
    path('reverse', views.MaskConfigListReverseView.as_view(), name='mask-list-reverse'),
    path('row/segment/edit/<int:pk>/', views.MaskSegmentUpdate.as_view(), name='update-masksegment-row'),
    path('list/segment/update/', views.SegmentListUpdate.as_view(), name='update-masksegment-list'),
    path('row/segment/update/<int:pk>/', views.MaskSegmentModalUpdate.as_view(), name='update-masksegment-modal'),
    path('row/segment/modal/update/', views.mask_modal_row, name='update-masksegment-modal-row'),
    path('mask/create/', views.MaterialMasterListView.as_view(), name='mask-create'),
    path('maskmanager/create/', views.MaskConfigCreateView.as_view(), name='maskmanager-create'),

    # ##### ooba ######
    path('ooba/list/', views.ooba_list_view, name='ooba_list'),
    path('ooba/create/', views.ooba_create_view, name='ooba_create'),


]

sfc/sfc/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import path

from django.contrib.auth import views as auth_views





urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('manufacturing/', include('manufacturing.urls')),
    path('config/git', include('git.urls')),
    path('config/', include('maskconfig.urls',namespace='maskconfig')),
    path('line/', include('line.urls')),
    path('line/', include('rules.urls')),
    path('api/', include('api.urls')),
    path('offline_station/', include('offline_station.urls')),
    path('shipping/', include('shipping.urls')),
    path('qms/', include('qms.urls')),
    path('wms/', include('wms.urls')),
    
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='manufacturing/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


from django.contrib.auth import views as auth_views
from django.urls import reverse
from django.urls import reverse_lazy
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),

    # path('password_reset/', auth_views.password_reset, name='password_reset'),
    # path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]


urlpatterns += [

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='registration/password_reset_formIMS.html',
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='registration/password_reset_doneIMS.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirmIMS.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_completeIMS.html'
         ),
         name='password_reset_complete'),
]


sfc/maskconfig/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.
from django.urls import reverse
import random
import string
from datetime import datetime, date
from django.apps import apps


class Segment(models.Model):
    row_id = models.AutoField(auto_created=True, primary_key=True)
    mask_id = models.ForeignKey('Mask', on_delete=models.CASCADE, null=True, db_column='mask_id')
    create_date = models.DateTimeField(auto_now=True)

    ######## editable ###########
    name = models.CharField(max_length=30)
    action = models.CharField(max_length=200)
    position = models.IntegerField(validators=[
        MinValueValidator(0),

    ]
    )
    ####### editable ###########

    TYPE_OF = (
        ('Hard Code', 'Hard Code'),
        ('Day', 'Day'),
        ('Week', 'Week'),
        ('Month', 'Month'),
        ('Year', 'Year'),
        ('Numeric', 'Numeric'),
        ('Alpha Numeric', 'Alpha Numeric'),
        ('Text', 'Text'),
        ('Model', 'Model')
    )

    data_type = models.CharField(
        max_length=20,
        choices=TYPE_OF,
        help_text='Type of data segment'
    )
    length = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)], null=True)
    value = models.CharField(max_length=15, null=True, blank=True)
    creator = models.CharField('Creator', max_length=20)
    create_date = models.DateTimeField('Create Date', auto_now=True)
    updater = models.CharField('Updater', max_length=20, null=True, blank=True)
    update_date = models.DateTimeField('Update Date', null=True, blank=True)

    # def __str__(self):
    #     return 'Model: ' + self.model.model + ' position ' + str(self.position)
    def get_absolute_url(self):
        """Returns the url to access a detail record """
        # return reverse('maskconfig:update-mask-row', args=[str(self.id)])
        return reverse('maskconfig:home')

    def __str__(self):
        return self.mask_id.model.model_id + ' Segment ' + str(self.position)

class Mask(models.Model):
    mask_id = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    model = models.ForeignKey('manufacturing.MaterialMaster',on_delete=models.SET_NULL, null=True)
    
    action = models.CharField(max_length=200)

    creator = models.CharField('Creator', max_length=20)
    create_date = models.DateTimeField('Create Date', auto_now=True)
    updater = models.CharField('Updater', max_length=20, null=True, blank=True)
    update_date = models.DateTimeField('Update Date', null=True, blank=True)

    def __str__(self):
        return self.model.model_id + ' Config'

    # ###### 2/25 ####
    def get_absolute_url(self):
        """Returns the url to access a detail record """
        # return reverse('maskconfig:update-mask-row', args=[str(self.id)])

        return reverse('maskconfig:home')

    def get_sequence(self, segments, serial_number):
        
        reset = False
        new_segment = ''
        # check week
        date_ref = date(datetime.now().year,
                        datetime.now().month,
                        datetime.now().day).isocalendar()

        week = date_ref[1]        
        
        if serial_number:
            serial_number = serial_number.serial_number

        if segments:
            index = 0
            segment = None

            for seg in segments:
                
                if seg.data_type == 'Week':
                    segment = seg
                    break
                else:
                    index += seg.length

            if segment:
                right_bound = index + segment.length

                if serial_number:

                    chunk = serial_number[index:right_bound]
                    # check if
                    if chunk.isnumeric():

                        chunk = int(chunk)
                        
                        if chunk == week:
                            pass
                        else:

                            segment = None
                            for seg in segments:
                                if seg.data_type == 'Numeric':
                                    segment = seg


                            for x in range(0, segment.length):
                                if x == segment.length-1:
                                    new_segment = new_segment + "1"
                                else:
                                    new_segment = new_segment + "0"

                            reset = True



        if segments and not reset:

            index = 0
            segment = None

            found = False

            for seg in segments:

                if seg.data_type == 'Numeric':

                    segment = seg
                    found = True


                elif found == False:

                    index += seg.length

            right_bound = 0

            if segment:
                right_bound = index + segment.length


                if serial_number:

                    chunk = serial_number[index:right_bound]

                    # check if
                    if chunk.isnumeric():

                        chunk = int(chunk)
                        chunk += 1

                        chunk = str(chunk)
                        if (len(chunk) > segment.length):
                            return ''
                        valid = False

                        # pad 0's until valid length
                        # will change later when rules are applied
                        while not valid:

                            if len(chunk) == segment.length:

                                valid = True
                            else:
                                chunk = '0' + chunk

                    new_segment = chunk
                else:

                    for i in range(segment.length):
                        new_segment += '0'

                
        return new_segment



    def generate_sn(self):
        
        
        segment_list = Segment.objects.filter(mask_id=self).order_by('position')
        if segment_list:
            segments = segment_list.values('row_id','position', 'length', 'value', 'data_type')
            segment_list = [entry for entry in segments] 

            serial_number = ''
            pattern = ''
            for segment in segment_list:

                if segment['data_type'] == 'Hard Code':
                    serial_number = str(serial_number + str(segment['value']))

                    # pattern

                    pattern = str(pattern + str(segment['value']))
                elif segment['data_type'] == 'Day':

                    pattern_symbol = 'D'

                    day = datetime.now().day

                    if day > 10:
                        day = '0' + str(day)
                    else:
                        day = str(day)

                    day = day[0:segment['length']]
                    serial_number = str(serial_number + day)

                    for i in range(len(day)):
                        pattern = str(pattern + pattern_symbol)

                elif segment['data_type'] == 'Week':

                    pattern_symbol = 'W'

                    date_ref = date(datetime.now().year,
                                    datetime.now().month,
                                    datetime.now().day).isocalendar()

                    week = date_ref[1]

                    if week < 10:
                        week = '0' + str(week)
                    else:
                        week = str(week)

                    week = week[0:segment['length']]
                    serial_number = str(serial_number + week)

                    for i in range(len(week)):
                        pattern = str(pattern + pattern_symbol)

                elif segment['data_type'] == 'Month':

                    pattern_symbol = 'M'

                    month = datetime.now().month

                    if month > 10:
                        month = '0' + str(month)
                    else:
                        month = str(month)

                    month = month[0:segment['length']]
                    serial_number = str(serial_number + month)

                    for i in range(len(month)):
                        pattern = str(pattern + pattern_symbol)

                elif segment['data_type'] == 'Year':

                    pattern_symbol = 'Y'

                    year = datetime.now().year

                    year = str(year)

                    if segment['length'] == len(year):
                        year = year
                    else:

                        year = year[-1:((len(year) - 1) - segment['length']):-1]

                        year = year[-1::-1]

                    serial_number = str(serial_number + year)

                    for i in range(len(year)):
                        pattern = str(pattern + pattern_symbol)

                elif segment['data_type'] == 'Numeric':
                    

                    SerialNumber = apps.get_model('manufacturing', 'SerialNumber')

                    seg_list = Segment.objects.filter(mask_id=self.mask_id).order_by('position')

                    MaterialMaster = apps.get_model('manufacturing', 'MaterialMaster')

                    material_ref = MaterialMaster.objects.filter(pk=self.model)
                    # get latest created
                    if (material_ref):
                        material_ref = material_ref.first()

                        sn_list = SerialNumber.objects.filter(model_id=material_ref)


sfc/maskconfig/forms.py
from django import forms
from django.core.validators import MinValueValidator
from .models import Mask, Segment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SegmentForm(forms.Form):
    position = forms.IntegerField(validators=[MinValueValidator(0)])
    TYPE_OF = (
        ('Hard Code', 'Hard Code'),
        ('Date', 'Date'),
        ('Numeric', 'Numeric'),
        ('Alpha Numeric', 'Alpha Numeric'),
        ('Text', 'Text'),
        ('Model', 'Model')
    )

    data_type = forms.ChoiceField(choices=TYPE_OF, widget=forms.Select(attrs={"onChange": 'validate()'}))
    name = forms.CharField(max_length=30)
    length = forms.IntegerField(validators=[MinValueValidator(0)], disabled=True)
    value = forms.CharField(max_length=30)

    def clean_position(self, *args, **kwargs):
        position = self.cleaned_data.get('position')
        if position > 0:
            return position
        else:
            raise forms.ValidationError('This is not a valid number(1,2,3,...')


class MaskForm(forms.Form):
    model = forms.CharField(max_length=20)


##### 3/13
class SegmentModalForm(forms.Form):
    mask = forms.CharField(max_length=30)
    position = forms.IntegerField(validators=[MinValueValidator(0)])
    name = forms.CharField(max_length=30)
    length = forms.IntegerField(validators=[MinValueValidator(0)], disabled=True)
    data_type = forms.CharField(max_length=30)


######### 2/26 create segment row
class SegmentRowForm(forms.Form):
    position = forms.IntegerField(validators=[MinValueValidator(0)])
    name = forms.CharField(max_length=30)
    length = forms.IntegerField(validators=[MinValueValidator(0)], disabled=True)

    def clean_position(self, *args, **kwargs):
        position = self.cleaned_data.get('position')
        if position > 0:
            return position
        else:
            raise forms.ValidationError('This is not a valid number(1,2,3,...')


sfc/maskconfig/templates/maskconfig/createsegment.html
{% include 'manufacturing/include/header.html' %}
{% load static %}
<link href="{% static 'css/maskconfig/style.css' %}" rel="stylesheet">
{% include 'manufacturing/include/sidebar.html' %}
    <section id="main-content">
        <section class="wrapper">
          <div class="row">
            <div class="col-lg-12">
              <ol class="breadcrumb">
                   <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Dashboard</a></li>
                    <!--<li><i class="icon_cogs"></i><a href="{% url 'manufacturing:sub_config' %}">Configuration</a></li>-->
                   <li><i class="fa fa-th-list"></i><a href="{% url 'maskconfig:home' %}">Mask Manager List</a></li>
                   <li><i class="fa fa-square-o"></i>Create Segment</li>
              </ol>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <section class="panel ">
                <div class="panel-body mask-container">
                  <form method="POST">
                      <section class="login-wrap mask-container">
                           <div class="form-group">
                            {% csrf_token %}
                               <input class="form-control"  type="number" name="position" required="" id="id_position" value="1" style="display: none;">
                               <label for="id_data_type">Data type:</label>
                                <select class="form-control"  name="data_type" onchange="validate()" id="id_data_type">
                                  <option value="Hard Code">Hard Code</option>
                                  <option value="Date">Day</option>
                                  <option value="Week">Week</option>
                                  <option value="Month">Month</option>
                                  <option value="Year">Year</option>
                                  <option value="Numeric">Numeric</option>
                                  <option value="Alpha Numeric">Alpha Numeric</option>
                                  <option value="Text">Text</option>
                                  <option value="Model">Model</option>
                               </select>
                               <label for="id_name">Name:</label>
                               <input class="form-control"  type="text" name="name" maxlength="30" required="" id="id_name">

                               <label for="id_length">Length:</label>
                               <input class="form-control"  type="number" name="length" required="" disabled="" id="id_length">

                               <label for="id_value">Value:</label>
                               <input class="form-control"  type="text" name="value" maxlength="100" required="" id="id_value">
                           </div>
                        <button class="btn btn-primary" type="submit">Submit</button>
                      </section>
                  </form>
                </div>

              </section>
            </div>
          </div>
      </section>
    </section>
<script src="{% static 'js/maskconfig/segment-validation.js' %}"></script>
{% include 'manufacturing/include/javascript-sidebar.html' %}

sfc/maskconfig/templates/maskconfig/editsegment.html
{% include 'manufacturing/include/header.html' %}
{% load static %}
<link href="{% static 'css/maskconfig/style.css' %}" rel="stylesheet">
{% include 'manufacturing/include/sidebar.html' %}
    <section id="main-content">
        <section class="wrapper">
          <div class="row">
            <div class="col-lg-12">
              <ol class="breadcrumb">
                   <li><i class="fa fa-home"></i><a href="{% url 'manufacturing:home' %}">Home</a></li>
                  <li><i class="fa fa-laptop"></i><a href="{% url 'manufacturing:sub_config' %}">Configuration</a></li>
                   <li><i class="fa fa-th-list"></i><a href="{% url 'maskconfig:home' %}">Mask Manager List</a></li>
                   <li><i class="fa fa-square-o"></i>Edit Segment</li>
              </ol>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12">
              <section class="panel ">
                <div class="panel-body mask-container">
                  <form method="POST">
                      <section class="login-wrap mask-container">
                           <div class="form-group">
                            {% csrf_token %}
                                <input hidden type="text" name="row_id" value={{row_id}}>
                               <label for="id_position">Position:</label>
                               <input class="form-control"  type="number" name="position" value={{position}} required="" id="id_position">

                               <label for="id_data_type">Data type:</label>
                               <select class="form-control"  name="data_type" onchange="validate()" id="id_data_type">
                                    {% if data_types %}
                                        {% for type in data_types %}
                                            <option value="{{type}}" {% if type == data_type %} selected {% endif %}>
                                                {{type}}
                                            </option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                               <label for="id_name">Name:</label>
                               <input class="form-control"  id="id_name"  type="text" name="name" maxlength="30" required="" value="{{name}}">

                               <label for="id_length">Length:</label>
                               <input class="form-control" id="id_length"  type="number" name="length" required="" disabled="" value="{{length}}" >

                               <label for="id_value">Value:</label>
                               <input class="form-control" id="id_value" type="text" name="value" maxlength="100" required="" value="{{value}}" >
                           </div>
                            <button class="btn btn-primary" type="submit">Submit</button>
                      </section>
                  </form>
                </div>
              </section>
            </div>
          </div>
      </section>
    </section>
<script src="{% static 'js/maskconfig/segment-validation.js' %}"></script>
{% include 'manufacturing/include/javascript-sidebar.html' %}

sfc/maskconfig/templates/maskconfig/maskmanager-list-search.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/maskconfig/style.css' %}">
<div id="maxheight">
{% include 'manufacturing/include/error-modal-style.html' %}
  {% if maskmanager_list %}
      <table class="table table-striped table-advance table-hover table-flex table-margin">
          <tbody>
            <tr id="table-header" class = "column table-header">
                {% load static %}
                {% if 'reverse' in request.path %}
                <th> <button class="icon-text"> <a href="{% url 'maskconfig:home' %}">&#8595; </a> <span>Order</span></button></th>
                {% elif '' in request.path %}
                <th> <button class="icon-text"> <a href="{% url 'maskconfig:mask-list-reverse' %}">&#8593; </a> <span>Order</span></button> </th>
                {% endif %}
                 <th></th>
                 <th ><i class="icon_grid-3x3"></i> &nbsp; Model</th>
                 <th ><i class="icon_profile"></i> &nbsp; User</th>
                 <th><i class="icon_check"></i> &nbsp; Action</th>
                 <th><i class="icon_cogs"></i>&nbsp; Actions</th>
                 <th>&nbsp;</th>
            </tr>
          </tbody>
         {% for mask in maskmanager_list %}
            <tr class="column">
                 {% if 'reverse' in request.path %}
                      <th><p>&nbsp;&nbsp;{{ forloop.counter }}</p></th>
                      {% elif '' in request.path %}
                      <th><p>&nbsp;&nbsp;{{ forloop.revcounter }}</p></th>
                      {% endif %}
                        <iframe name="formDestination" style="display: none;"></iframe>
                        <form action="{% url 'maskconfig:update-mask-row' mask.pk  %}" method="post" enctype="multipart/form-data" target="formDestination">
                             {% csrf_token %}
                             {{ form.non_field_errors }}
                             {{ form.source.errors }}
                            {{ form.source }}
                            <th><input type="hidden" name="chk"/>&nbsp;&nbsp;</th>
                            <th class="col-xs-3 column-action">
                                <div class="edit-save-1 hover" id="edit-save-1">
                                   <p><input type="text" class="edit-input-1 edit-row" name="model" value="{{ mask.model }}"></p>
                               </div>
                            </th>
                            <th class="col-xs-3"> <p>{{ mask.creator }}</p></th>
                            <th class="col-xs-6"><p>{{ mask.action }}</p></th>
                             <th class="column-action">
                                 <div class="mask-ul" style="display: flex; justify-content: center;">
                                     <div>
                                        <button type="submit" id="save-button-1"  style="background: none; border: none;" class="icon-text-mask icon-text  btn-confirm simple-confirm" >
                                        <img  src="{% static 'svg/submit-id.svg' %}" alt="icon"><span>Save</span></button>
                                     </div>
                         </form>
                               <div>
                                    <form action= "{% url 'maskconfig:segments' %}" method="GET">
                                          <input type="hidden" name='model_number' value="{{ mask.model }}">
                                          <button type="submit"  style="background: none; border: none;" class="icon-text-mask icon-text  btn-confirm simple-confirm" >
                                          <img  src="{% static 'svg/generate.svg' %}" alt="icon"><span>Modify</span></button>
                                    </form>
                               </div>
                                  <div>
                                    <form onsubmit="return confirm('Confirm delete?');" action="{% url 'maskconfig:delete-mask-row' mask.pk %}" method="post">
                                      {% csrf_token %}
                    <!--                    <input type="hidden" name='model_number' value="{{ mask.model }}">-->
                                      <button type="submit"  style="background: none; border: none;" class="icon-text">
                                        <img src="{% static 'svg/delete.svg' %}" alt="icon"><span>Delete</span></button>
                                    </form>
                                  </div>
                         </div>
                   </th>
                   <th>&nbsp;</th>
            </tr>
             {% empty %}
              <div id="myModal" class="modal-log">
                 <div class="modal-content"  style="width: 40%;">
                     <span class="close" data-dismiss="modal" style="z-index: 100;">×</span>
                      <div class="warning-modal-body">
                         <p>No related data</p>
                       </div>
                   </div>
                <button style="display: none;" id="myBtn">Open Modal</button>
             </div>
        {% endfor %}
        {% else %}
        <div id="myModal" class="modal-log">
                 <div class="modal-content"  style="width: 40%;">
                     <span class="close" data-dismiss="modal" style="z-index: 100;">×</span>
                      <div class="warning-modal-body">
                         <p>No related data found</p>
                       </div>
                   </div>
                <button style="display: none;" id="myBtn">Open Modal</button>
             </div>
        {% endif %}
              <table  class="table table-striped table-advance table-hover table-flex">
                <tbody>
                   <div class = "column">
                        <!-- ############## page  ############## -->
                        {% include 'manufacturing/include/pagination.html' %}
                        <!-- #################### end page #########   -->
                   </div>
                 </tbody>
            </table>
        <form id="hi" action="/config" method="POST"></form>
        </div>
{% load static %}
<script src="{% static 'js/line/warning-modal.js' %}"></script>
<script src="{% static 'js/manufacturing/inline.js' %}"></script>